### PR TITLE
Enforce setcap ordering when installing from repo

### LINKED ISSUE #92: Module tries to do setcap on the binary before it's been installed
When using settings like this in my hiera:

```
    "vault::default_lease_ttl": "720h",
    "vault::manage_user": false,

    "vault::install_method": "repo",
    "vault::package_name": "vault",
    "vault::bin_dir": "/usr/local/bin",
    "vault::manage_service_file": true
```

The module seems to try to call setcap on the binary before the installation has taken place

```
[vault3] Notice: /Stage[main]/Aptrepo::Client/Exec[apt-get-update-private-repo]/returns: executed successfully
[vault3] Notice: /Stage[main]/Vault::Install/Exec[setcap cap_ipc_lock=+ep /usr/local/bin/vault]/returns: Failed to set capabilities on file `/usr/local/bin/vault' (Invalid argument)
[vault3] Notice: /Stage[main]/Vault::Install/Exec[setcap cap_ipc_lock=+ep /usr/local/bin/vault]/returns: The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
[vault3] Error: setcap cap_ipc_lock=+ep /usr/local/bin/vault returned 1 instead of one of [0]
[vault3] Error: /Stage[main]/Vault::Install/Exec[setcap cap_ipc_lock=+ep /usr/local/bin/vault]/returns: change from notrun to 0 failed: setcap cap_ipc_lock=+ep /usr/local/bin/vault returned 1 instead of one of [0]
[vault3] Notice: /Stage[main]/Vault::Install/Package[vault]/ensure: created
[vault3] Notice: /Stage[main]/Vault::Config/File[/etc/systemd/system/vault.service]: Dependency Exec[setcap cap_ipc_lock=+ep /usr/local/bin/vault] has failures: true
[vault3] Warning: /Stage[main]/Vault::Config/File[/etc/systemd/system/vault.service]: Skipping because of failed dependencies
[vault3] Notice: /Stage[main]/Vault::Config/Exec[systemd-reload]: Dependency Exec[setcap cap_ipc_lock=+ep /usr/local/bin/vault] has failures: true
[vault3] Warning: /Stage[main]/Vault::Config/Exec[systemd-reload]: Skipping because of failed dependencies
[vault3] Notice: /Stage[main]/Vault::Config/File[/etc/vault]: Dependency Exec[setcap cap_ipc_lock=+ep /usr/local/bin/vault] has failures: true
[vault3] Warning: /Stage[main]/Vault::Config/File[/etc/vault]: Skipping because of failed dependencies
[vault3] Notice: /Stage[main]/Vault::Config/File[/etc/vault/config.json]: Dependency Exec[setcap cap_ipc_lock=+ep /usr/local/bin/vault] has failures: true
[vault3] Warning: /Stage[main]/Vault::Config/File[/etc/vault/config.json]: Skipping because of failed dependencies
[vault3] Notice: /Stage[main]/Vault::Service/Service[vault]: Dependency Exec[setcap cap_ipc_lock=+ep /usr/local/bin/vault] has failures: true
[vault3] Warning: /Stage[main]/Vault::Service/Service[vault]: Skipping because of failed dependencies
[vault3] Notice: Applied catalog in 12.26 seconds

Done.
```

Running puppet a second time works as expected (since it was installed in the first run above):

```
[vault3] Notice: /Stage[main]/Vault::Install/File[/usr/local/bin/vault]/mode: mode changed '0755' to '0555'
[vault3] Notice: /Stage[main]/Vault::Install/Exec[setcap cap_ipc_lock=+ep /usr/local/bin/vault]/returns: executed successfully
[vault3] Notice: /Stage[main]/Vault::Install/Exec[setcap cap_ipc_lock=+ep /usr/local/bin/vault]: Triggered 'refresh' from 1 events
[vault3] Notice: /Stage[main]/Vault::Config/File[/etc/systemd/system/vault.service]/ensure: defined content as '{md5}5573833f7041000e0d40e06f105b51bd'
[vault3] Notice: /Stage[main]/Vault::Config/Exec[systemd-reload]: Triggered 'refresh' from 1 events
[vault3] Notice: /Stage[main]/Vault::Config/File[/etc/vault]/ensure: created
[vault3] Notice: /Stage[main]/Vault::Config/File[/etc/vault/config.json]/ensure: defined content as '{md5}76b452f557bbe35be8ff89d2676c07ec'
[vault3] Notice: /Stage[main]/Vault::Service/Service[vault]/ensure: ensure changed 'stopped' to 'running'
[vault3] Notice: Applied catalog in 7.60 seconds
```

I'll poke around and see if I can create a PR for this issue.

### PR DESCRIPTION
**Pull request by optiz0r**
##### SUMMARY
Adds a dependency between package installation and setting file
capabilities when using the repo installation method. Without this,
setcap is attempted before the vault binary exists, and causes the
puppet run to fail.

##### TESTS/SPECS
Includes updated spec test that ensures ordering of capability when
enabled an package is installed via repository only.

Change has been validated in production on CentOS 7.5, puppet 4.x

Fixes #92

### CODE REVIEW

File: spec/classes/vault_spec.rb [hunk 1]
```diff
@@ -197,9 +197,17 @@
           it { is_expected.not_to contain_file_capability('vault_binary_capability') }
 
           context 'when managing file capabilities' do
-            let(:params) { { manage_file_capabilities: true } }
+            let(:params) do
```
Comment (jsok) [inline spec/classes/vault_spec.rb:200]: Instead of duplicating the params from the parent context can you merge them like:

```
let(:params) do
  super().merge(manage_file_capabilities: true)
end
```

**Review by jsok — COMMENTED** [review]
Logic is good, just a small DRY in the spec.

CI failures appear unrelated, just [re-ran master build](https://travis-ci.org/jsok/puppet-vault/builds/399933260) and it's failing there too. rubocop constantly breaks 😟

**Review by jsok — APPROVED** [review]

**Comment by jsok** [comment]
I've fixed the build failures in master. Will merge once the CI build goes green.
Thanks for your contribution.
